apiVersion:  eksctl.io/v1alpha5
kind:  ClusterConfig

metadata:
  name: genaisergecluster
  region: eu-west-3
  version: "1.31"

nodeGroups:
  - name: onlynode
    instanceType: t4g.medium
    desiredCapacity: 1
    volumeSize: 10
    # minSize: 1
    # maxSize: 1
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyName: clusterkey