name: mygpt
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
  backend:
    environment:
      tavily_key : /run/secrets/tavily_api_key
    build:
      secrets:
        - tavily_key
      context: ./backend
secrets:
  tavily_key:
    file: ./tavily_secret.txt


